### ISSUE TITLE
Fails on dots in hash keys

### ISSUE THREAD

**Issue by cbetta** [jm/toml#20]
To replicate:

``` sh
$ data = {"foo.bar" => "value" }
$ File.write('test.tml',  TOML::Generator.new(data).body)
$ TOML.load_file("test.tml")
Failed to match sequence (ALL_SPACE (KEY_GROUP / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE) at line 1 char 1.
`- Don't know what to do with "foo.bar = " at line 1 char 1.
NoMethodError: undefined method `each' for nil:NilClass
  from /Users/username/.rvm/gems/ruby-1.9.3-p448@gemset/gems/toml-0.0.4/lib/toml/parser.rb:21:in `initialize'
  from /Users/username/.rvm/gems/ruby-1.9.3-p448@gemset/gems/toml-0.0.4/lib/toml.rb:24:in `new'
  from /Users/username/.rvm/gems/ruby-1.9.3-p448@gemset/gems/toml-0.0.4/lib/toml.rb:24:in `load_file'
  from (irb):8
  from /Users/username/.rvm/rubies/ruby-1.9.3-p448/bin/irb:16:in `<main>'
```

**Comment by biewers** [comment]
I assume this defect is still open because [dotted keys](https://github.com/toml-lang/toml#user-content-keys) are indeed supported and the gem still does not support them? Is there any plan to add support for them? This issue is 6 years old now. Really just curious. Obvious workarounds exist.
